a = int(input("Nhap vao a"))
b = int(input("Nhap vao b"))

print("{0}+{1}={2}".format(a, b, a+b))
print("{0}-{1}={2}".format(a, b, a-b))
print("{0}*{1}={2}".format(a, b, a*b))
print("{0}/{1}={2}".format(a, b, a/b))
print("{0}**{1}={2}".format(a, b, a**b))
print("{0}//{1}={2}".format(a, b, a//b))
print("{0}%{1}={2}".format(a, b, a%b))